 ### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "rut": "123456789",
  "username": "testuser",
  "email": "testuser@email.com",
  "password": "password123"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@email.com",
  "password": "password123"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1234"
}

### Get profile (requires JWT)
GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw

### Logout (requires JWT)
POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw

### Get all users
GET http://localhost:5000/api/users/allUsers

### Create account (requires JWT)
POST http://localhost:5000/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw
Content-Type: application/json

{
  "type": "SAVINGS"
}

### Get user's accounts (requires JWT)
GET http://localhost:5000/api/account/myAccounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZjQ1OGRlZDhmY2FlZmU5ODZhZWRlMSIsImlhdCI6MTc2MDkyNzMwNSwiZXhwIjoxNzYwOTI4MjA1fQ.h0PFKe1OkZL-yhQEgyCStCzNIdqZQTiKAv7hDWWerqA

GET http://localhost:5000/api/account/myAccounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZjQ1OGRlZDhmY2FlZmU5ODZhZWRlMSIsImlhdCI6MTc2MDkyNzMwNSwiZXhwIjoxNzYwOTI4MjA1fQ.h0PFKe1OkZL-yhQEgyCStCzNIdqZQTiKAv7hDWWerqA


### Update account (requires JWT)
PATCH http://localhost:5000/api/account/updateAccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw
Content-Type: application/json

{
  "id": "68edce8e0aa9a0e6cc767824",
  "type": "SAVINGS",
  "balance": 1000,
  "isActive": true
}

### Delete account (requires JWT)
DELETE http://localhost:5000/api/account/68edce8e0aa9a0e6cc767824
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDgyMjgzNiwiZXhwIjoxNzYwODIzNzM2fQ.K5WpSoY4BUkCDV_y1yHJsiM2wHee6q52ryFXJQWNDek

### Create card (requires JWT)
POST http://localhost:5000/api/card
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw
Content-Type: application/json

{
  "accountId": "68edce8e0aa9a0e6cc767824",
  "password": "4321"
}

### Get account's cards (requires JWT)
GET http://localhost:5000/api/card/myCards?accountId=68f458ded8fcaefe986aede4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZjQ1OGRlZDhmY2FlZmU5ODZhZWRlMSIsImlhdCI6MTc2MDkyNzMwNSwiZXhwIjoxNzYwOTI4MjA1fQ.h0PFKe1OkZL-yhQEgyCStCzNIdqZQTiKAv7hDWWerqA

### Update card (requires JWT)
PATCH http://localhost:5000/api/card/updateCard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw
Content-Type: application/json

{
  "id": "68d99221cabf2dde826ed1d5",
  "cvv": 123,
  "number": "4111111111111111",
  "penalties": 0,
  "spentLimit": 5000,
  "accessPassword": "cardpassword"
}

### Delete card (requires JWT)
DELETE http://localhost:5000/api/card/68d99221cabf2dde826ed1d5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInN1YiI6IjY4ZWRjZThlMGFhOWEwZTZjYzc2NzgyMSIsImlhdCI6MTc2MDQ2ODc2MywiZXhwIjoxNzYwNDY5NjYzfQ.I7SOcAuqmfDLIeEtwLhhymFfP6YfATkPyueBzP4mRpw